name: npchain-infra

on:
  workflow_dispatch:
  push:
    paths:
      - 'Infrastructure/**'  # Capital 'I' to match your folder structure

env:
  RESOURCE_GROUP: aguadamillas_students_1
  SUBSCRIPTION_ID: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: npchain

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    # Fixed indentation here
      - uses: actions/checkout@v2
      - name: Run Bicep Linter
        run: az bicep build --file ./Infrastructure/main.bicep  # Fixed path
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: 'Development'
    
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ./Infrastructure/main.bicep  # Fixed path
          parameters: ./Infrastructure/parameters/dev.bicepparam  # Fixed path
          deploymentName: ${{ env.USER_ALIAS }}