name: david-infra

on:
  workflow_dispatch:
  push:
    paths:
      - 'Infrastructure/**'

env:
  RESOURCE_GROUP: BCSAI2024-DEVOPS-STUDENTS-A-DEV
  SUBSCRIPTION_ID: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: david

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Run Bicep Linter
        run: az bicep build --file ./Infrastructure/main.bicep
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
    
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ./Infrastructure/main.bicep
          parameters: ./Infrastructure/parameters/dev.bicepparam
          deploymentName: ${{ env.USER_ALIAS }}